Run commands and scripts to windows hosts
rundeck-plugins/ansible-plugin pull request #112
Opened 2017-05-24 18:47 UTC by ltamaster

Add option to run commands, scripts (Node Executor and File Copier) to windows hosts, it required winrm support on the ansible server (see http://docs.ansible.com/ansible/intro_windows.html)

Also, fix an issue getting the nodes form Ansible when the host has defined the attribute ansible_host equal to null

2017-08-09 18:58 UTC, frozenice commented on src/main/java/com/batix/rundeck/plugins/AnsibleResourceModelSource.java
> +          if (root.has("ansible_os_family")) {
Are you sure this mapping for OsFamily and OsName to Ansible facts is correct (haven't tested it)?

2017-08-09 19:00 UTC, frozenice commented
Needs a rebase / merge so the CI can run.

2017-08-09 19:59 UTC, DerekTBrown commented on src/main/java/com/batix/rundeck/plugins/AnsibleResourceModelSource.java
> +          if (root.has("ansible_os_family")) {
I doubt it very much

2017-08-09 20:00 UTC, DerekTBrown requested changes
This would break the "choose default shell" option.  Need to add a setting for Windows users.

2017-08-10 02:45 UTC, ltamaster commented on src/main/java/com/batix/rundeck/plugins/AnsibleResourceModelSource.java
> +          if (root.has("ansible_os_family")) {
Hi, this worked for me on ansible 2.3.1.0.

<img width="717" alt="screenshot 2017-08-09 22 39 52" src="https://user-images.githubusercontent.com/6034968/29152145-b84ed582-7d53-11e7-8117-f4f5afd042e4.png">

<img width="1252" alt="screenshot 2017-08-09 22 44 34" src="https://user-images.githubusercontent.com/6034968/29152236-59822e9a-7d54-11e7-810e-baefcb8a83f9.png">

2017-08-10 15:10 UTC, ltamaster commented
Hi @DerekTBrown 
About the "choose default shell" option.
By default I didn't set the executor for windows hosts. If I add it (and if I add new options on "choose default shell" for windows, like cmd.exe or powershell.exe) the plugin will lose the option (by default)  to manage multiples OS on the same project (because a default value like bash/sh will fail on windows host ). Of course in this case the workaround will be that the user overwrites the ansible-executor at node level, but that would need that the user create another resource model manually.

So, I was thinking to  define a default executor on the Model Resource for windows host like:

<img width="889" alt="screenshot 2017-08-10 10 57 05" src="https://user-images.githubusercontent.com/6034968/29177049-a78e9d8c-7dbb-11e7-8e09-6b43520dcac0.png">

Of course, the disadvantage will be if the user wants to use another default shell.

Another workaround is to add a second "choose default shell" but for windows hosts.

Please let me know what you think about it.

Thanks
Luis

2017-08-10 20:33 UTC, DerekTBrown commented
@ltamaster I like the idea of a second option better than fixing it to Powershell, it is cleaner.

2017-08-15 19:22 UTC, ltamaster commented
Hi @DerekTBrown, 

I added the second option for windows

<img width="1229" alt="screenshot 2017-08-15 16 02 45" src="https://user-images.githubusercontent.com/6034968/29332302-f4bc32f4-81d5-11e7-9c74-b21148da91ad.png">

2017-09-06 17:35 UTC, ltamaster commented
Hi @DerekTBrown,

This is a friendly follow up, is the new settings (Windows Executable)  looks OK for you?

Thanks
Luis

2017-09-06 22:29 UTC, DerekTBrown commented
@ltamaster looks good to me!  I know that @frozenice was working on some CI tests for this package so that we can validate further commits, so I was initially going to hold off until we could integrate this into the test suite.  However, it doesn't seem like that is going to happen soon, so I am going to merge this under the assumption that we will need to write some CI tests for Windows systems later.

2017-09-06 22:29 UTC, DerekTBrown approved these changes

2017-09-06 22:29 UTC, merged