Dockerfile edits
rundeck-plugins/ansible-plugin pull request #171
Opened 2018-01-31 22:55 UTC by cityofships

- PR #167 inadvertently introduced incorrect order of variables - `RDECK_BASE` must be defined before others
- Bump Rundeck version to newest 2.10.5 from 26.01.2018
- Further optimizations - 3 RUN statements merged into 1

2018-01-31 23:21 UTC, mcassaniti requested changes
Thanks for the PR. Overall it looks good. Please move the COPY lines after the RUN line, with the ansible-plugin COPY line last. I'd be more likely to update those files in quick succession than to change the packages or Rundeck launcher version. This helps when making use of Docker's build caching.

2018-01-31 23:32 UTC, cityofships commented
Fair enough

2018-01-31 23:35 UTC, cityofships commented
However, this breaks putting `chmod +x /run.sh` in the single RUN statement

2018-01-31 23:42 UTC, mcassaniti commented
The chmod is annoying, but I'm going with having it in a separate RUN command. I wish single file copies came with an option to set permissions at the same time. You can check-in /run.sh in the repo with the correct permissions, but if you build on a non-UNIX OS (and I can bet someday someone will) then your COPY will likely have the wrong permission bits.

2018-02-07 21:21 UTC, mcassaniti approved these changes
Thanks for the effort you've put in.

2018-02-07 21:23 UTC, merged