RUN-671: Code changes for transferred Ansible Repo
rundeck-plugins/ansible-plugin pull request #310
Opened 2022-03-23 21:19 UTC by qualman

2022-03-29 19:50 UTC, ltamaster requested changes

2022-03-29 19:50 UTC, ltamaster commented on docker/project.properties
> +service.NodeExecutor.default.provider=com.rundeck.plugins.ansible.plugin.AnsibleNodeExecutor
this hasn't changed, the name is set here 
https://github.com/rundeck-plugins/ansible-plugin/blob/enh/RUN-671_migrate_repo-220310/src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSourceFactory.java#L17

https://github.com/rundeck-plugins/ansible-plugin/blob/enh/RUN-671_migrate_repo-220310/src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleFileCopier.java#L27

https://github.com/rundeck-plugins/ansible-plugin/blob/enh/RUN-671_migrate_repo-220310/src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleNodeExecutor.java#L25

2022-03-30 15:54 UTC, qualman commented on docker/project.properties
> +service.NodeExecutor.default.provider=com.rundeck.plugins.ansible.plugin.AnsibleNodeExecutor
I am not sure how my find and replaces missed this.... thank you!

2022-03-30 16:41 UTC, ltamaster commented
now I am thinking that we shouldn't change the provider name because of this
<img width="1278" alt="Screen Shot 2022-03-30 at 13 39 48" src="https://user-images.githubusercontent.com/6034968/160887276-2e8c612c-8552-44e7-83dc-8573770ede29.png">

it will break existing projects

2022-03-30 17:55 UTC, ltamaster commented
well for resource-model, node-executor and file-copier it is easy to migrate (just replace project.properties with the new name) 
```
resources.source.2.type=com.rundeck.plugins.ansible.plugin.AnsibleResourceModelSourceFactory
service.FileCopier.default.provider=com.rundeck.plugins.ansible.plugin.AnsibleFileCopier
service.NodeExecutor.default.provider=com.rundeck.plugins.ansible.plugin.AnsibleNodeExecutor
```

but for jobs, that will be harder because you will need to export them, change the provider names and import them:

<img width="1766" alt="Screen Shot 2022-03-30 at 14 52 09" src="https://user-images.githubusercontent.com/6034968/160900201-d7543a63-915f-4f98-94f0-fb6208e91d7d.png">

<img width="1309" alt="Screen Shot 2022-03-30 at 14 52 16" src="https://user-images.githubusercontent.com/6034968/160900150-dcd1258c-9e9c-401a-badf-f9b53883d40d.png">

2022-03-30 18:35 UTC, qualman commented
Ok @ltamaster , see if this latest change makes those jobs work for you?

2022-03-30 20:33 UTC, ltamaster approved these changes
tested

2022-03-30 23:17 UTC, merged