Fixing ANSIBLE_BINARIES_DIR_PATH resolution
rundeck-plugins/ansible-plugin pull request #342
Opened 2023-09-27 12:42 UTC by Simon-cto

Changed to the PropertyResolver.resolveProperty method to get the correct resolution (jobconf first, then projectconf).

#331

2023-10-18 22:58 UTC, ltamaster approved these changes

2023-10-18 23:03 UTC, ltamaster requested changes

2023-10-18 23:03 UTC, ltamaster commented on src/main/groovy/com/rundeck/plugins/ansible/ansible/AnsibleRunnerBuilder.java
>          return binariesFilePathStr;
to maintain the original behavior, this code should be added
```suggestion
        if (null != binariesFilePathStr) {
            if (binariesFilePathStr.contains("${")) {
                return DataContextUtils.replaceDataReferences(binariesFilePathStr, getContext().getDataContext());
            }
        }
        return binariesFilePathStr;
```

2023-11-08 13:27 UTC, Simon-cto reviewed
Adding requested code to replace data references

2023-11-09 14:47 UTC, ltamaster approved these changes

2023-11-09 14:47 UTC, merged